#!/bin/bash

match=$(cd etc && cat passwd | cut -d":" -f5 | cut -d" " -f2 )

if [ "$1" == "" ]
then
	echo "Comando falta o sobrenome"
else
	if [ "$match" == "" ]
	then
		echo "Sobrenome não existe"
	else
		echo $(cd etc && cat passwd | grep $1 | cut -d":" -f5)
	fi
fi

exit
