#!/bin/bash

echo Introduza um nome de utilizador 
read nome
echo Introduza o diretorio a listar
read diretorio
echo "Estes são os ficheiros no diretorio /$diretorio da área de trabalho do utilizador
$nome na data $(date):"

exit
