#!/bin/bash

match=$(cd etc && cat passwd | cut -d":" -f1 | grep $1)

if [ "$1" == "" ]
then
	echo "Comando falta o utilizador"
else
	if [ "$match" == "" ]
	then
		echo "Utilizador não existe"
	else
		echo "Utilizador existe"
		echo $(cd etc && cat passwd | grep $1 | cut -d":" -f5,6,7)
	fi
fi

exit
