#!/bin/bash

#TODO
#aceitar apenas parametros que existem

recolherDados()
{
	#Verifica que o ficheiro para o dia existe
	if [ -f ./report/"$nomPraia"/"$j"/"$ano-$j-$k.txt" ]
	then
		#Este comando vai buscar o dado 
		dado=$(cat ./report/"$nomPraia"/"$j"/"$ano-$j-$k.txt" | grep $param | cut -d":" -f2)
		echo  "$ano-$j-$k;$dado" >> "${nomPraia}_$param.csv"
	fi
	#Se não existir, o programa simplesmente salta para outro dia
}

#Verifica se o diretorio report existe
if [ ! -d report ]
then
	#O diretorio report não existe
	echo "Ficheiro Clientes.txt está a faltar"
else
	#Verifica que foram introduzidos argumentos
	if [ "$#" = 0 ]
	then
		#Não foi introduzido argumento nenhum
		echo "Erro: Introduza um parametro"
	else
		param=$1
		#Verifica que o parametro introduzido existe
		if [ "$param" = "TPMR" ] || [ "$param" = "VVEN" ] || [ "$param" = "A" ] || [ "$param" = "B" ]
		then
			numPraias=$(find ./report -maxdepth 1 -mindepth 1 -type d | wc -l)
			#Verifica que há praias introduzidas
			if [ "$numPraias" = "0" ]
			then
				#Neste caso não há praias logo é impossivel fazer alguma coisa
				echo "Não existem praias registadas"
			else
				#Vai buscar os dados de uma praia individual
				for (( i=1; i<=$numPraias; i++ ))
				do				
					nomPraia=$(find ./report -maxdepth 1 -mindepth 1 -type d | cut -c 10- | head -$i | tail -1 )
					#Ciclo for dedicado aos meses
					for (( j=1; j<=12; j++))
					do
						numAnos=$(ls report/"$nomPraia"/"$j"| grep -o "^...." | uniq | wc -l)
						#Ciclo for dedicado aos vários anos que possam estar incluidos dentro de cada mês
						for (( anoCont=1; anoCont<=$numAnos; anoCont++ ))
						do	
							ano=$(ls report/"$nomPraia"/"$j"| grep -o "^...." | uniq | head -$anoCont | tail -1)
							#Meses com 31 dias
							if [ "$j" = "1" ] || [ "$j" = "3" ] || [ "$j" = "5" ] || [ "$j" = "7" ] || [ "$j" = "8" ] || [ "$j" = "10" ] || [ "$j" = "12" ]
							then
								#Ciclo for dedicado a um dia individual
								for (( k=1; k<=31; k++ ))
								do
									recolherDados                   
								done
							#Este é para o mês de fevereiro
							elif [ "$j" = "2" ]
							then
								#Assumindo que anos bissextos não existem
								for (( k=1; k<=28; k++ ))
								do
									recolherDados			
								done
							#Este é para os meses com 30 dias
							else
								for (( k=1; k<=30; k++ ))
								do
									recolherDados
								done
							fi
							echo -en "\rMês $j da praia $i concluido."
						done
					done
				done
			fi
			echo ""
		else
			echo "ERRO: Parâmetro inexistente"
		fi
	fi
fi

exit
