#!/bin/bash

varDados()
{
    #Gera uma variação "Moderada" de temperatura do mar e do vento
    rand=$(shuf -i0-1 -n1)
    delta=$(shuf -i0-2 -n1)
    if [ "$rand" = "1" ]
    then
        tempMar=$(( tempMar + delta ))
        velVento=$(( velVento + delta ))
    else
        tempMar=$(( tempMar - delta ))
        velVento=$(( velvento - delta ))
    fi
    
    marAlto=$(( marAlto + rand ))
    marBaixo=$(( marAlto + 6 ))
    #Dá reset ao mar alto caso ele chegue ás 12h da manha
    if [ "$marAlto" = "13" ]
    then
        marAlto=4
    fi
    
    #Verifica que não há dados impossiveis
    if [ "$tempMar" -gt 23 ] 
    then
        tempMar=23
	elif [ "$tempMar" -lt 4 ]
	then
		tempMar=4
    fi 
    if [ "$velVento" -gt 16 ]
    then
        velVento=16
	elif [ "$velVento" -lt 8 ]
	then
		velVento=8
    fi 
}

escreverRel()
{
	a=$(shuf -i2016-2019 -n 1)
    nomFicheiro="$a-$j-$k.txt"        
    #Função que varia ligeiramente os dados
    varDados
    echo -e "TPMR:$tempMar\nVVEN:$velVento\nA:$marAlto\nB:$marBaixo" > ./report/"$nomPraia"/"$j"/$nomFicheiro   
}


###################MAIN#################################

#Verifica se o diretório report existe e apaga-o se já existir
cd ..
if [ ! -d report ]
then
	#O diretorio report nao existe
	mkdir report
else
	#O diretorio report existe
	rm -rf report
	mkdir report	
fi

if [ -z "$1" ]
then
	echo "Temos que introduzir um argumento a especificar o numero de praias a gerar"
else
	temporizador=0
    tempMar=14
    velVento=12
    marAlto=4
	for (( i=1; i<=$1; i++ ))
	do	
		#Gera a pasta com o nome da praia
		nomPraia=$(shuf -n 1 ./gerar/nomPraias)

        #Verifica se o nome da praia já não foi escolhida antes
		limLista=$(find ./report -maxdepth 1 -type d | cut -c 3- | wc -l)
		for (( lista=2; lista<=$limLista; lista++ ))        
		do
			nomeTeste=$(find ./report -maxdepth 1 -type d | cut -c 10- | head -$lista | tail -1)
			#So serve para teste echo "$nomPraia = $nomeTeste"
			if [ "$nomPraia" = "$nomeTeste" ]
			then
				#DEBUG: echo "Nome duplicado encontrado"
				nomPraia=$(shuf -n 1 ./gerar/nomPraias)
				lista=1
			fi
        done 

		mkdir ./report/"$nomPraia"
		
		#Gera 12 pastas para cada mês
		for (( j=1; j<=12; j++))
		do
			mkdir ./report/"$nomPraia"/"$j"
			
			#Gera os ficheiros dentro de cada mês
			#Meses com 31 dias
			if [ "$j" = "1" ] || [ "$j" = "3" ] || [ "$j" = "5" ] || [ "$j" = "7" ] || [ "$j" = "8" ] || [ "$j" = "10" ] || [ "$j" = "12" ]
			then
				for (( k=1; k<=31; k++ ))
				do
					escreverRel                   
				done
			#Este é para o mês de fevereiro
			elif [ "$j" = "2" ]
			then
				#Assumindo que anos bissextos não existem
			    for (( k=1; k<=28; k++ ))
				do
                	escreverRel			
				done
			#Este é para os meses com 30 dias
			else
				for (( k=1; k<=30; k++ ))
				do
					escreverRel
				done
			fi
            echo -en "\rMês $j da praia $i concluido."
		done
	done
fi

tempo=$(( SECONDS - temporizador))
echo -en "\rOperação Concluida em $tempo segundos\n"

exit
