#!/bin/bash

resultado=$(find | wc -l)
resultado=$((resultado - 1))
echo Existem $resultado ficheiros e diretorios e subdiretorios 

#Para contar o número de ficheiros num diretorio
numFicheiros=$(ls -p | grep -v / | wc -l)
#echo $numFicheiros no diretorio atual. 

#ls -p| grep -v / | head -contador (ficheiro) | tail -1 -> para obter o diretorio
for (( i=1; i<=$numFicheiros; i++ ))
do
	nomFicheiro=$(ls -p| grep -v / | head -$i | tail -1)
	numPalavras=$(cat $nomFicheiro | wc -w)
	numLinhas=$(cat $nomFicheiro | wc -l)
	echo No ficheiro $nomFicheiro existem $numPalavras palavras e $numLinhas linhas.
done

echo "Fim do programa"

exit

