#!/bin/bash

memDirAtual=$(du -h | grep -v / | cut -f1)
echo "O espaço ocupado em disco pelo diretório atual é $memDirAtual"

#Compila a lista de ficheiros com mais de 1MB
grandeFicheiro=$(find -size +1M | tr -d "./")
numGrandeFicheiro=$(find -size +1M | wc -l)
echo "Há $numGrandeFicheiro ficheiros com mais de 1Mb, entre eles estes são:"
echo $grandeFicheiro

exit
