#!/bin/bash

#Verifica se o ficheiro Clientes.txt existe e cria um novo se ja existir, ou cria se nao existir
if [ ! -f Clientes.txt ]
then
	touch Clientes.txt
else
	rm Clientes.txt
	touch Clientes.txt
fi

if [ -z "$1" ]
then
	echo "Temos que introduzir um argumento a especificar o numero de clientes a especificar"
else
	temporizador=0
	for (( i=1; i<=$1; i++ ))
	do
		#Primeiro nome
		primNome=$(shuf -n 1 primNome)

		#Sobrenome
		sobrNome=$(shuf -n 1 sobrNome)

		#Plafond
		random=$(shuf -i 0-1 -n 1)
		if [ "$random" = "1" ]
		then
			plafond="S"
		else
			plafond="N"
		fi

		#Codigo Postal
		random=$(shuf -i 1000-9999 -n 1)
		codigoPostal=$random
		random=$(shuf -i 100-999 -n 1)
		codigoPostal=$(echo $codigoPostal-$random)

		#NIF
		#Aqui tem intencionalmente um erro que permite gerar NIFs com mais(ou menos) de 9 números para poder fazer um exercicio que verifica se os NIFs estão corretos ou não
		nif=$(shuf -i 99999999-1000000000 -n 1)

		#Tipo Produto
		tipProd=$(shuf -n 1 tipProd)
		
		echo "$primNome $sobrNome;$plafond;$codigoPostal;$nif;$tipProd" >> "Clientes.txt"
		echo -en "\rCliente $i gerado"
	done
fi

mv ./Clientes.txt ../Clientes.txt

tempo=$(( SECONDS - temporizador))
echo -en "\rOperação Concluida em $tempo segundos\n"

exit
