#!/bin/bash

#Verifica se o ficheiro Clientes.txt existe
if [ ! -f Clientes.txt ]
then
	#O ficheiro Clientes.txt não existe e por isso é impossivel correr o script
	echo "Ficheiro Clientes.txt está a faltar"
else 
	#Este if verifica se o ficheiro de output já existe e se existir apaga e cria um novo
	if [ ! -f nifValido.txt ]
	then
		#Neste caso não existe por isso o ficheiro é criado
		touch nifValido.txt
	else
		#Neste caso existe por isso é apagado e criado de novo
		rm nifValido.txt
		touch nifValido.txt
	fi
	#Estas flags vão servir mais tarde para escrever o erro
	erro=""
	erro1=""
	#Esta variavel conta o tempo
	tempo=$SECONDS
	#Vai buscar o número de clientes para poder correr no loop
	numeroClientes=$(cat Clientes.txt | wc -l)
	for (( i=1; i<=$numeroClientes; i++ )) 
	do	
		#Vai buscar o nif de cada cliente individual
		nif=$(cut -d";" -f4 < Clientes.txt | head -$i | tail -1)
		#Este if verifica se o NIF possui 9 digitos
		if [ "$nif" -gt "999999999" ] || [ "$nif" -lt 100000000 ]
		then	
			#Neste caso o NIF tem mais ou menos do que 9 digitos
			erro="NIF não possui exatamente 9 digitos"
		else
			#Neste caso o NIF tem o número correto de digitos
			erro=""
		fi

		#Este if verifica se o NIF começa em 1,2,5,6,8 ou 9
		if echo $nif | grep -q "^1" || echo $nif | grep -q "^2" || echo $nif | grep -q "^5" || echo $nif | grep -q "^6" || echo $nif | grep -q "^8" || echo $nif | grep -q "^9"
		then
			erro1=""
		else
			erro1="NIF não começa por 1, 2, 5, 6, 8 ou 9"
		fi 
		
		#Este if escreve o erro para o utilizador
		if [ "$erro" = "" ] && [ "$erro1" = "" ]
		then
			echo "O cliente $i possui um NIF válido => NIF: $nif" >> "nifValido.txt"
		else
			echo "O cliente $i NÃO possui um NIF válido, causa: $erro $erro1 => NIF: $nif" >> "nifValido.txt"
		fi
		echo -en "\rCliente $i verificado"
	done
	tempo=$(( SECONDS - tempo))
	echo -en "\rOperação efetuada em $tempo s.\nResultado encontra-se em nifValido.txt\n"
fi

exit
