#!/bin/bash

#Verifica se o ficheiro Clientes.txt existe
if [ ! -f Clientes.txt ]
then
	#O ficheiro Clientes.txt não existe e por isso é impossivel correr o script
	echo "Ficheiro Clientes.txt está a faltar"
else 
	#Verifica se foram passados argumentos
	if [ "$#" -gt "0" ]
	then
		echo "Tipo Produto : Número de ocorrências"
		#Isto é necessário porque não sabemos quantos argumentos vão ser passados pelo utilizador
		for (( i=1; i<=$# ; i++)) 
		do
			#Este comando vai buscar o argumento individual á lista do $@
			argumento=$(echo $@ | cut -d" " -f$i)
			#Este comando corta para apenas a 5 linha(para não encontrar sem querer uma pessoa com o nome Torradeira e contar o número errado de vezes) e depois conta o número de vezes que o argumento é encontrado
			numVezes=$(cut -d";" -f5 < Clientes.txt | grep -w "$argumento" | wc -l)
			echo "$argumento : $numVezes vezes"
		done
	else
		#Não foram passados argumentos por isso não se pode fazer nada
		echo "Não foram passados argumentos"
	fi
fi

exit
