GET http://localhost:8080/api HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/api/bears HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/api/bears HTTP/1.1
Content-Type: application/json

{
    "name" : "Mr. Bearimy"
}

###

GET http://localhost:8080/api/bears/5f916985a1cb5448bc5dece6 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8080/api/bears/5f916985a1cb5448bc5dece6 HTTP/1.1
Content-Type: application/json

{
    "name" : "Poo"
}

###

DELETE http://localhost:8080/api/bears/5f916985a1cb5448bc5dece6 HTTP/1.1
Content-Type: application/json